version: '3.8'

services:
  chat-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"  # Порт для WebSocket-сервера
      - "2222:22"    # Порт для SSH (локальный 2222 мапится на 22 в контейнере)
    volumes:
      - .:/app  # Монтирование текущей директории в /app
    environment:
      - DEBIAN_FRONTEND=noninteractive
    tty: true
    stdin_open: true
    command: /usr/sbin/sshd -D


networks:
  default:
    driver: bridge
    name: docker_free
