version: '3.9'
services:

  chat-gateway:
    container_name: chat-gateway-2
    build: .
    image: chat-gateway-image-2
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - .:/project
    environment:
      - TZ=UTC
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: docker_free
